name: smrit_driver
description: SMRIT Fleet Management — Driver App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # HTTP
  dio: ^5.4.0

  # GPS
  geolocator: ^11.0.0
  permission_handler: ^11.3.1

  # State management
  flutter_riverpod: ^2.5.0

  # Storage
  flutter_secure_storage: ^9.0.0

  # Utils
  intl: ^0.19.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
